import {
  Bell,
  Captions,
  Cloud,
  Database,
  Download,
  Gauge,
  HardDrive,
  Layers,
  Mail,
  Image,
  Network,
  Paintbrush,
  PlayCircle,
  Puzzle,
  Search,
  ScanSearch,
  ScrollText,
  Settings2,
  Sparkles,
  Subtitles,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

import type { SettingsSearchGroup, SettingsSearchItem } from "@/components/settings/settingsSearch";

export interface AdminSettingsSearchItem extends SettingsSearchItem {
  id: string;
  label: string;
  description: string;
  keywords?: readonly string[];
  settings?: readonly { label: string; description?: string; keywords?: readonly string[] }[];
  icon: LucideIcon;
}

export type AdminSettingsSearchGroup = SettingsSearchGroup<AdminSettingsSearchItem>;

const settingIndex = (...labels: string[]) => labels.map((label) => ({ label }));

// Tab ids are stable URL state (?tab=...) — regroup or reorder freely, but
// renaming an id breaks bookmarks and deep links.
export const ADMIN_SETTINGS_GROUPS: AdminSettingsSearchGroup[] = [
  {
    label: "Server",
    items: [
      {
        id: "general",
        label: "General",
        description: "Authentication, token lifetimes, and server logging.",
        keywords: ["access token", "refresh token", "expiry", "log level", "quiet subsystems"],
        settings: settingIndex(
          "Access Token Expiry",
          "Refresh Token Expiry",
          "Log Level",
          "Quiet Subsystems",
        ),
        icon: Settings2,
      },
      {
        id: "branding",
        label: "Branding",
        description: "White-label logo, favicon, server name, login background, and accent color.",
        keywords: [
          "logo",
          "wordmark",
          "icon",
          "favicon",
          "white label",
          "brand",
          "login background",
          "accent color",
          "default theme",
          "app name",
          "pwa",
        ],
        settings: settingIndex(
          "Server Name",
          "Login Page Subtitle",
          "Logo (wordmark)",
          "Logo (icon)",
          "Favicon",
          "Login Background",
          "Brand Accent Color",
          "Default Theme",
        ),
        icon: Image,
      },
      {
        id: "theming",
        label: "Theming",
        description: "Server theme token overrides, custom CSS, and the theme catalog.",
        keywords: ["theme", "custom css", "community themes", "appearance", "token overrides"],
        settings: settingIndex("Preview", "Token Overrides", "Custom CSS", "Theme Catalog URL"),
        icon: Paintbrush,
      },
      {
        id: "overlays",
        label: "Card Overlays",
        description: "Server-wide poster badge and overlay defaults.",
        keywords: ["poster", "badges", "defaults.card_overlays", "overlay preset"],
        settings: settingIndex(
          "Card Overlays Enabled",
          "Default Configuration",
          "Default style preset",
          "Overlay position",
          "Overlay enabled",
        ),
        icon: Layers,
      },
    ],
  },
  {
    label: "Media",
    items: [
      {
        id: "scanner",
        label: "Scanner & Matcher",
        description: "Scan workers, matcher workers, batch size, and image caching.",
        keywords: ["scanner workers", "matcher workers", "batch size", "metadata cache images"],
        settings: settingIndex(
          "Scanner Workers",
          "Matcher Workers",
          "Matcher Batch Size",
          "Cache Images to S3",
        ),
        icon: ScanSearch,
      },
      {
        id: "search",
        label: "Search",
        description: "Catalog search provider, Meilisearch connection, and index maintenance.",
        keywords: [
          "catalog search",
          "meilisearch",
          "postgres fts",
          "full text search",
          "index",
          "typo tolerance",
          "batch size",
          "index scope",
          "semantic search",
          "hybrid search",
          "vectors",
          "embeddings",
          "embedder",
          "binary quantization",
          "quantized",
        ],
        settings: settingIndex(
          "Preferred Provider",
          "URL",
          "API Key",
          "Index Prefix",
          "Timeout (ms)",
          "Matching Strategy",
          "Sync Batch Size",
          "Rebuild Batch Size",
          "Rebuild Queue Depth",
          "Indexed Types",
          "Semantic Search",
          "Semantic Ratio",
          "Embedder",
          "Vectorized Documents",
          "Status",
        ),
        icon: Search,
      },
      {
        id: "intro",
        label: "Intro Markers",
        description: "Marker lookup mode, playback fetches, providers, and submissions.",
        keywords: [
          "intro",
          "credits",
          "recap",
          "markers",
          "chapter markers",
          "provider contributions",
        ],
        settings: settingIndex(
          "Mode",
          "Fetch Markers at Playback if Missing",
          "Use for Online Marker Lookup",
          "Allow Contributions",
          "Auto-submit Local Markers",
          "Marker Providers",
        ),
        icon: Captions,
      },
      {
        id: "subtitles",
        label: "Subtitles",
        description: "Downloaded subtitles, provider settings, and subtitle appearance.",
        keywords: ["opensubtitles", "providers", "subtitle language", "caption", "downloaded"],
        settings: settingIndex(
          "Provider settings",
          "Downloaded subtitles",
          "Subtitle appearance",
          "Subtitle language",
          "Subtitle behavior",
          "Forced subtitles",
        ),
        icon: Subtitles,
      },
      {
        id: "ai",
        label: "AI Services",
        description: "AI provider endpoints, translation, transcription, and quotas.",
        keywords: [
          "openai",
          "ollama",
          "base url",
          "api key",
          "chat model",
          "translation",
          "transcription",
          "subtitles",
          "quota",
        ],
        settings: settingIndex(
          "Text translation",
          "Base URL",
          "Chat model",
          "API Key",
          "Test Text AI",
          "Speech-to-text",
          "Transcription model",
          "Transcription base URL",
          "Transcription API key",
          "Test Speech-to-Text",
          "Features",
          "Max concurrent jobs",
          "Subtitle translation",
          "Subtitle generation from audio",
          "Description translation",
          "On-view translation",
          "Subtitle batch size",
          "Subtitle context lines",
          "Transcription chunk length (seconds)",
          "Transcription limit per account",
          "Transcription limit period",
          "Advanced",
        ),
        icon: Sparkles,
      },
      {
        id: "playback",
        label: "Playback",
        description: "FFmpeg, transcoding, hardware acceleration, segments, and resume behavior.",
        keywords: [
          "ffmpeg",
          "transcode",
          "hardware acceleration",
          "chapter thumbnails",
          "watched threshold",
          "resume threshold",
          "4k",
        ],
        settings: settingIndex(
          "FFmpeg Path",
          "Transcode Directory",
          "Hardware Acceleration",
          "Transcoding Enabled",
          "Local Transcode Fallback",
          "Allow 4K Transcoding",
          "Enable Transcode Throttling",
          "Throttle Buffer (seconds)",
          "Chapter Thumbnail Workers",
          "Chapter Thumbnail Execution",
          "Chapter Thumbnail Node Capacity",
          "HDR Chapter Thumbnail Policy",
          "Enable CPU Tone Mapping",
          "Watched Threshold (%)",
          "Min Resume Threshold (%)",
        ),
        icon: PlayCircle,
      },
      {
        id: "downloads",
        label: "Downloads",
        description: "Download enablement, bandwidth, concurrency, and period limits.",
        keywords: ["bandwidth", "concurrent downloads", "download limit", "period duration"],
        settings: settingIndex(
          "Downloads Enabled",
          "Server Bandwidth (Mbps)",
          "Per-User Bandwidth (Mbps)",
          "Max Concurrent Downloads Per User",
          "Max Downloads Per Period",
          "Period Duration",
        ),
        icon: Download,
      },
    ],
  },
  {
    label: "Connections",
    items: [
      {
        id: "watch-providers",
        label: "Watch Providers",
        description: "Provider integrations for watch history and scrobbling.",
        keywords: ["trakt", "simkl", "import", "export", "scrobble", "watch history", "favorites"],
        settings: settingIndex(
          "Trakt Client ID",
          "Trakt Client Secret",
          "Simkl Client ID",
          "Simkl Client Secret",
        ),
        icon: Cloud,
      },
      {
        id: "integrations",
        label: "Integrations",
        description: "Third-party integration keys and service connections.",
        keywords: ["mdblist", "api key", "metadata lists"],
        settings: settingIndex("API Key"),
        icon: Puzzle,
      },
      {
        id: "email",
        label: "Email",
        description: "SMTP delivery, sender address, digest schedule, and external URL.",
        keywords: ["smtp", "mail", "from address", "digest", "external url", "tls"],
        settings: settingIndex(
          "Email Enabled",
          "From Address",
          "From Name",
          "Host",
          "Port",
          "Security",
          "Username",
          "Password",
          "Verify",
        ),
        icon: Mail,
      },
      {
        id: "notifications",
        label: "Notifications",
        description:
          "Server notification channels, release events, Silo Push Relay, Discord, web push, and webhooks.",
        keywords: [
          "release events",
          "new episode",
          "silo push relay",
          "mobile push",
          "apple push",
          "android push",
          "apns",
          "push relay",
          "privacy disclosure",
          "discord",
          "browser push",
          "web push",
          "webhooks",
          "server channels",
        ],
        settings: settingIndex(
          "Record events",
          "Enable release events",
          "Fan out",
          "Enable fanout",
          "Delivery Channels",
          "In-App",
          "Web Push",
          "Silo Push Relay",
          "Relay URL",
          "Deployment ID",
          "Register Relay",
          "Clear Relay Credential",
          "Privacy Disclosure",
          "Email",
          "Allow Per-Episode Email",
          "Digest Hour",
          "External URL",
          "Discord",
          "Client ID",
          "Client Secret",
          "Bot Token",
          "Invite Bot to Server",
          "Clear Discord Credentials",
          "Allow Per-Episode DMs",
          "Embed Posters",
          "Personal Webhooks",
          "Max Webhooks Per Profile",
          "Deliveries Per Minute Per Profile",
          "Allow Private Destinations",
          "Server Channels",
          "Batch Window (seconds)",
          "Mention Requesters on Discord",
          "Settle Delay (seconds)",
          "Max Series Burst",
          "Max Event Age (hours)",
          "Read Notifications (days)",
          "Unread Notifications (days)",
          "Processed Events (days)",
        ),
        icon: Bell,
      },
      {
        id: "compatibility-proxies",
        label: "Compatibility Proxies",
        description: "Jellyfin and Audiobookshelf compatibility proxy settings.",
        keywords: ["jellyfin", "audiobookshelf", "abs", "public url", "server id", "session ttl"],
        settings: settingIndex(
          "Public URL",
          "Server Name",
          "Server ID",
          "Emulated Server Version",
          "Session TTL",
          "Playback Session TTL",
          "Enable Audiobookshelf Proxy",
        ),
        icon: Network,
      },
      {
        id: "rate-limiting",
        label: "Rate Limiting",
        description: "Request limits, API tiers, admin limits, and authentication throttles.",
        keywords: ["limits", "tiers", "requests", "throttle", "429", "api keys"],
        settings: settingIndex(
          "Enable Rate Limiting",
          "Backend",
          "Global Requests Per Second",
          "Per-IP Limits",
          "Requests / Second",
          "Requests / Minute",
          "Burst",
          "Standard",
          "Elevated",
          "Login",
          "Signup",
          "Setup",
          "Authentication endpoints",
        ),
        icon: Gauge,
      },
    ],
  },
  {
    label: "Data",
    items: [
      {
        id: "database",
        label: "Database",
        description: "Postgres, Redis, user database pooling, and Litestream settings.",
        keywords: [
          "postgres",
          "redis",
          "connection url",
          "user db",
          "pool",
          "litestream",
          "stale grace",
        ],
        settings: settingIndex(
          "Max Connections",
          "Enable Redis",
          "Connection URL",
          "User DB Backend",
          "Pool Max Open",
          "Idle Timeout",
          "Litestream Sync Interval",
          "Stale Grace Seconds",
        ),
        icon: Database,
      },
      {
        id: "storage",
        label: "Storage",
        description: "Public and private S3 storage buckets, endpoints, and credentials.",
        keywords: ["s3", "bucket", "endpoint", "region", "access key", "secret key", "uploads"],
        settings: settingIndex(
          "Endpoint",
          "Region",
          "Path Style",
          "Bucket",
          "Access Key",
          "Secret Key",
          "URL Auth Method",
          "Read Endpoint",
          "Token Secret",
          "Token Param",
          "Token TTL (seconds)",
        ),
        icon: HardDrive,
      },
      {
        id: "log-retention",
        label: "Log Retention",
        description:
          "Operations log cleanup, policy decision log cleanup, access log cleanup, and retention policies.",
        keywords: [
          "ops log",
          "access log",
          "policy decision log",
          "decision log",
          "opa",
          "cleanup",
          "retention",
          "history",
        ],
        settings: settingIndex(
          "Retention Days",
          "Max Rows",
          "Max Size (MB)",
          "Decision Log Retention Days",
          "Decision Log Verbosity",
          "Scope Sample Rate",
          "Bucket Overrides",
        ),
        icon: ScrollText,
      },
    ],
  },
];

export const ADMIN_SETTINGS_NAV = ADMIN_SETTINGS_GROUPS.flatMap((group) => group.items);
